### ISSUE TITLE
Add postecss-nested plugin to get nesting to work

### ISSUE THREAD

**Issue by joshRpowell** [progapandist/evil_chat#2]
Great framework and explained really well.  Thank you!

Ran into one blocker along the way. 

Needed to add postcss-nested plugin:

```
yarn add postcss-nested
```

```yml
/* .postcssrc.yml */

plugins:
  postcss-smart-import: {}
  postcss-cssnext: {}
  + postcss-nested: {}
```

in order to get nesting to work here `frontend/components/auth-form/auth-form.css`
